name: Push new version to dist branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push new version to dist branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3.1.0
      with:
        node-version: 16.x
    - name: yarn install and build
      run: |
        yarn install --immutable --immutable-cache --check-cache
        yarn build:prod

    - name: Push new version
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
